### ISSUE TITLE
/touchgrass as alias for /top

### ISSUE THREAD

**Issue by Waradu** [0PandaDEV/Nextron#32]
to get teleported to the highest grass block of your current position to get out of any cave instant (or just /touch <block_name> and if no block specified go to highest block)

**Comment by Waradu** [comment]
HaS tHIs beEN iMpLemEnted YEt?

**Comment by 0PandaDEV** [comment]
> HaS tHIs beEN iMpLemEnted YEt?

cAn yOu bElIeVe wHaT I HaVe dOnE?

**Comment by Waradu** [comment]
🌊

**Comment by 0PandaDEV** [comment]
https://github.com/0PandaDEV/Nextron/commit/55afb5d5f53edda14c443931998f0762ecf6c265 hihi
