### ISSUE TITLE
Feature request: /tpahere

### ISSUE THREAD

**Issue by obvTiger** [0PandaDEV/Nextron#33]

**Comment by inboxinstinct** [comment]
+1 my players would love to have this, was about to open this feature request myself.

**Comment by 0PandaDEV** [comment]
this was implemented and released in [1.5.7](https://github.com/0PandaDEV/Nextron/releases/tag/v1.5.7) https://github.com/0PandaDEV/Nextron/commit/30251c72b232a9eac15e0a188b6a74ed9f941239
