### ISSUE TITLE
Feature Request: Spawn System

### ISSUE THREAD

**Issue by obvTiger** [0PandaDEV/Nextron#8]
Spawn control like EssentialsX

**Comment by 0PandaDEV** [comment]
describe what you mean by spawn system

**Comment by obvTiger** [comment]
Spawnpoint control, per-player spawns

**Comment by 0PandaDEV** [comment]
ok i will look into it

**Comment by 0PandaDEV** [comment]
Is implemented in the newest commit https://github.com/0PandaDEV/Nextron/commit/52de8ef3bf623eac95c83ecd714ad6278c7d11ea, will be released in 1.5.0 soon.
