### ISSUE TITLE
Switch from the anvil rank name input to a chat based one since it is not long enough for formatted messages.

### ISSUE THREAD

**Issue by obvTiger** [0PandaDEV/Nextron#81]

**Comment by 0PandaDEV** [comment]
This will probably be implemented in 1.6.0

**Comment by 0PandaDEV** [comment]
Partially implemented to all inputs that are not triggered from a GUI https://github.com/0PandaDEV/Nextron/commit/180e9ce8e133217cc8412cc16ca2ce504281aba6
